#!/usr/bin/env python3
"""
Watch production JavaScript and sync it into a Tampermonkey preview file.

Usage:
  cp .env.local.example .env.local   # first-time setup
  pip install -r requirements.txt
  python3 scripts/watch_js.py        # watch for changes
  python3 scripts/watch_js.py --once # sync once and exit
"""

from __future__ import annotations

import argparse
import difflib
from datetime import datetime
import sys
import threading
import time
import webbrowser
from dataclasses import dataclass
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from preview_server import PREVIEW_PORT, start_preview_server, stop_preview_server

ROOT = SCRIPT_DIR.parent
DEFAULT_ENV_PATH = ROOT / ".env.local"

# --- defaults (override via .env.local) ---
DEFAULT_SOURCE_JS = "main/main.js"
DEFAULT_OUTPUT_DIR = "preview"
DEFAULT_PREVIEW_NAME = "js-local-preview"


@dataclass
class Config:
    site_url: str
    preview_name: str
    source_js: Path
    output_path: Path


def load_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing config file: {path}")

    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, raw = line.partition("=")
        values[key.strip()] = raw.strip()
    return values


def load_config(env_path: Path) -> Config:
    env = load_env(env_path)

    site_url = env.get("SITE_URL", "").strip()
    if not site_url:
        raise ValueError("Site URL is required — set SITE_URL in .env.local")

    preview_name = env.get("JS_LOCAL_PREVIEW_NAME",
                           DEFAULT_PREVIEW_NAME).strip() or DEFAULT_PREVIEW_NAME
    source_js = ROOT / env.get("SOURCE_JS", DEFAULT_SOURCE_JS).strip()
    output_dir = ROOT / env.get("OUTPUT_DIR", DEFAULT_OUTPUT_DIR).strip()
    output_path = output_dir / f"{preview_name}.js"

    return Config(
        site_url=site_url,
        preview_name=preview_name,
        source_js=source_js,
        output_path=output_path,
    )


def indent_js(js: str) -> str:
    return "\n".join(f"    {line}" if line else "" for line in js.splitlines())


def build_preview_js(source: str, config: Config) -> str:
    source_relative = config.source_js.relative_to(ROOT).as_posix()
    body = indent_js(source.rstrip())
    return f"""// Auto-generated by scripts/watch_js.py — do not edit.
// Source: {source_relative}
//
// {source_relative} is inlined below as-is for local preview.
// Copy {source_relative} to the CMS unchanged — see js-example.js for format.

(function () {{
  "use strict";

  const PREVIEW_PREFIX = "[hl-js-local-preview:preview]";

  try {{
{body}
    console.log(PREVIEW_PREFIX + " Main script executed successfully");
  }} catch (error) {{
    console.error(PREVIEW_PREFIX + " Runtime error:", error);
  }}
}})();
"""


def format_change_timestamp() -> str:
    return datetime.now().strftime("%I:%M %p").lstrip("0")


def normalize_source(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def source_is_equal(previous: str | None, current: str) -> bool:
    if previous is None:
        return False
    return normalize_source(previous) == normalize_source(current)


def count_line_changes(old: str, new: str) -> tuple[int, int]:
    diff = difflib.unified_diff(
        old.splitlines(),
        new.splitlines(),
        lineterm="",
    )
    added = 0
    removed = 0
    for line in diff:
        if line.startswith("+") and not line.startswith("+++"):
            added += 1
        elif line.startswith("-") and not line.startswith("---"):
            removed += 1
    return added, removed


def print_sync_status(
    config: Config,
    previous_source: str | None,
    source: str,
    *,
    changed: bool,
) -> None:
    ts = format_change_timestamp()
    rel_source = config.source_js.relative_to(ROOT)
    if not changed:
        print(f"[{ts}] Unchanged {rel_source}")
        return
    if previous_source is None:
        line_count = len(source.splitlines())
        print(f"[{ts}] Preview rebuilt from {rel_source} ({line_count} lines)")
        return
    added, removed = count_line_changes(
        normalize_source(previous_source),
        normalize_source(source),
    )
    if added == 0 and removed == 0:
        print(f"[{ts}] Unchanged {rel_source}")
        return
    print(f"[{ts}] Preview rebuilt from {rel_source} (+{added} / -{removed})")


def print_ready_status(config: Config, *, serve: bool) -> None:
    source = config.source_js.relative_to(ROOT)
    output = config.output_path.relative_to(ROOT)

    print()
    print("JS Local Preview Ready")
    print()
    print(f"Site URL:    {config.site_url}")
    print(f"Source:      {source}")
    print(f"Output:      {output}")
    if serve:
        print(f"Preview URL: {preview_url(config)}")
        print()
        print("Next steps:")
        print("1. Ensure tampermonkey-loader.user.js is installed in Tampermonkey")
        print("2. DevTools console — filter for hl-js-local-preview")
        print(f"3. Opening dev site: {config.site_url}")
        print()


def sync_preview(config: Config, previous_source: str | None, *, log_change: bool = False) -> str | None:
    if not config.source_js.is_file():
        print(
            f"error: source JS not found: {config.source_js.relative_to(ROOT)}", file=sys.stderr)
        return None

    source = config.source_js.read_text(encoding="utf-8")
    preview = build_preview_js(source, config)
    config.output_path.parent.mkdir(parents=True, exist_ok=True)

    preview_unchanged = (
        config.output_path.exists()
        and config.output_path.read_text(encoding="utf-8") == preview
    )
    source_unchanged = source_is_equal(previous_source, source)

    if preview_unchanged:
        if log_change and (source_unchanged or previous_source is not None):
            print_sync_status(config, previous_source, source, changed=False)
        return source

    config.output_path.write_text(preview, encoding="utf-8")
    if log_change:
        print_sync_status(config, previous_source, source, changed=True)
    return source


def preview_url(config: Config) -> str:
    rel = config.output_path.relative_to(ROOT).as_posix()
    return f"http://127.0.0.1:{PREVIEW_PORT}/{rel}"


def open_dev_site_tab(config: Config) -> None:
    """Open SITE_URL from .env.local — Tampermonkey runs the loader on this page."""
    webbrowser.open(config.site_url)


def watch(config: Config, env_path: Path, *, serve: bool, open_browser: bool) -> int:
    try:
        from watchdog.events import FileSystemEventHandler
        from watchdog.observers import Observer
    except ImportError:
        print("error: install watchdog first: pip install -r requirements.txt", file=sys.stderr)
        return 1

    previous_source: str | None = None
    sync_targets = {config.source_js.resolve(), env_path.resolve()}
    debounce_seconds = 0.15

    class Handler(FileSystemEventHandler):
        def __init__(self) -> None:
            super().__init__()
            self._timer: threading.Timer | None = None
            self._timer_lock = threading.Lock()

        def _schedule_sync(self, path: Path) -> None:
            resolved = path.resolve()
            if resolved not in sync_targets:
                return

            def run_sync() -> None:
                nonlocal previous_source
                result = sync_preview(config, previous_source, log_change=True)
                if result is not None:
                    previous_source = result

            with self._timer_lock:
                if self._timer is not None:
                    self._timer.cancel()
                self._timer = threading.Timer(debounce_seconds, run_sync)
                self._timer.daemon = True
                self._timer.start()

        def on_modified(self, event) -> None:
            if event.is_directory:
                return
            self._schedule_sync(Path(event.src_path))

        def on_created(self, event) -> None:
            if event.is_directory:
                return
            self._schedule_sync(Path(event.src_path))

        def on_moved(self, event) -> None:
            if event.is_directory:
                return
            self._schedule_sync(Path(event.dest_path))

    previous_source = sync_preview(config, previous_source)
    if previous_source is None:
        return 1

    if serve:
        try:
            start_preview_server()
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

    print_ready_status(config, serve=serve)
    if serve and open_browser:
        open_dev_site_tab(config)

    print("Watching for changes...")
    observer = Observer()
    handler = Handler()
    observer.schedule(handler, str(config.source_js.parent), recursive=False)
    observer.schedule(handler, str(env_path.parent), recursive=False)
    observer.start()

    print("Press Ctrl+C to stop.")
    print()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print()
        observer.stop()
    observer.join()

    if serve:
        stop_preview_server()

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--env",
        type=Path,
        default=DEFAULT_ENV_PATH,
        help="Path to .env.local (default: .env.local in repo root)",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Sync once and exit (no file watching)",
    )
    parser.add_argument(
        "--no-serve",
        action="store_true",
        help="Do not start the built-in preview server",
    )
    parser.add_argument(
        "--no-open",
        action="store_true",
        help="Do not open SITE_URL from .env.local in a browser tab",
    )
    args = parser.parse_args()

    env_path = args.env.resolve()
    try:
        config = load_config(env_path)
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    serve = not args.no_serve
    open_browser = not args.no_open

    if args.once:
        ok = sync_preview(config, None) is not None
        if ok and serve:
            try:
                start_preview_server()
            except RuntimeError as exc:
                print(f"error: {exc}", file=sys.stderr)
                return 1
        if ok:
            print_ready_status(config, serve=serve)
            if serve and open_browser:
                open_dev_site_tab(config)
            if serve:
                print("Press Ctrl+C to stop.")
                print()
                try:
                    while True:
                        time.sleep(3600)
                except KeyboardInterrupt:
                    print()
                stop_preview_server()
        return 0 if ok else 1

    return watch(config, env_path, serve=serve, open_browser=open_browser)


if __name__ == "__main__":
    from watch import main as watch_main

    raise SystemExit(watch_main(["js", *sys.argv[1:]]))
